// ─── Mock Data ───────────────────────────────────────────────────────────────
export const MOCK_PEOPLE = [
  {
    personID: 1,
    firstName: "Ahmed",
    lastName: "Benali",
    nationalNumber: "AB123456",
    phone: "+212 6 12 34 56 78",
    email: "ahmed.benali@example.com",
    address: "123 Avenue Mohammed V",
    city: "Casablanca",
    gender: "Male",
    association: "user",
    associationDetails: { type: "Admin", username: "ahmed.b" },
  },
  {
    personID: 2,
    firstName: "Fatima",
    lastName: "Zahra",
    nationalNumber: "FZ789012",
    phone: "+212 6 98 76 54 32",
    email: "fatima.zahra@example.com",
    address: "45 Rue de la Liberté",
    city: "Rabat",
    gender: "Female",
    association: "member",
    associationDetails: { type: "Student", membershipDate: "2025-09-15" },
  },
  {
    personID: 3,
    firstName: "Youssef",
    lastName: "El Amrani",
    nationalNumber: "YE345678",
    phone: "+212 6 55 44 33 22",
    email: "youssef.amrani@example.com",
    address: "78 Boulevard Hassan II",
    city: "Marrakech",
    gender: "Male",
    association: "user",
    associationDetails: { type: "Librarian", username: "youssef.e" },
  },
  {
    personID: 4,
    firstName: "Amina",
    lastName: "Tazi",
    nationalNumber: "AT901234",
    phone: "+212 6 11 22 33 44",
    email: "amina.tazi@example.com",
    address: "12 Rue Oued El Makhazine",
    city: "Fes",
    gender: "Female",
    association: "none",
    associationDetails: null,
  },
  {
    personID: 5,
    firstName: "Karim",
    lastName: "Idrissi",
    nationalNumber: "KI567890",
    phone: "+212 6 77 88 99 00",
    email: "karim.idrissi@example.com",
    address: "56 Avenue des FAR",
    city: "Tangier",
    gender: "Male",
    association: "member",
    associationDetails: { type: "Faculty", membershipDate: "2024-03-10" },
  },
  {
    personID: 6,
    firstName: "Nadia",
    lastName: "Bennani",
    nationalNumber: "NB123789",
    phone: "+212 6 44 55 66 77",
    email: "nadia.bennani@example.com",
    address: "34 Rue Allal Ben Abdellah",
    city: "Agadir",
    gender: "Female",
    association: "user",
    associationDetails: { type: "Staff", username: "nadia.b" },
  },
  {
    personID: 7,
    firstName: "Hassan",
    lastName: "Ouazzani",
    nationalNumber: "HO456123",
    phone: "+212 6 33 22 11 00",
    email: "hassan.ouazzani@example.com",
    address: "89 Boulevard Mohammed VI",
    city: "Oujda",
    gender: "Male",
    association: "none",
    associationDetails: null,
  },
  {
    personID: 8,
    firstName: "Samira",
    lastName: "El Fassi",
    nationalNumber: "SF789456",
    phone: "+212 6 66 77 88 99",
    email: "samira.elfassi@example.com",
    address: "23 Rue de la Plage",
    city: "El Jadida",
    gender: "Female",
    association: "member",
    associationDetails: { type: "Staff", membershipDate: "2025-01-20" },
  },
  {
    personID: 9,
    firstName: "Omar",
    lastName: "Bouazza",
    nationalNumber: "OB321654",
    phone: "+212 6 99 88 77 66",
    email: "omar.bouazza@example.com",
    address: "67 Avenue de l'Université",
    city: "Meknes",
    gender: "Male",
    association: "user",
    associationDetails: { type: "Admin", username: "omar.b" },
  },
  {
    personID: 10,
    firstName: "Leila",
    lastName: "Chraibi",
    nationalNumber: "LC654987",
    phone: "+212 6 22 33 44 55",
    email: "leila.chraibi@example.com",
    address: "15 Rue Atlas",
    city: "Kenitra",
    gender: "Female",
    association: "none",
    associationDetails: null,
  },
  {
    personID: 11,
    firstName: "Rachid",
    lastName: "Mansouri",
    nationalNumber: "RM147258",
    phone: "+212 6 88 77 66 55",
    email: "rachid.mansouri@example.com",
    address: "90 Boulevard Zerktouni",
    city: "Casablanca",
    gender: "Male",
    association: "member",
    associationDetails: { type: "Student", membershipDate: "2025-06-01" },
  },
  {
    personID: 12,
    firstName: "Mouna",
    lastName: "Hassani",
    nationalNumber: "MH369258",
    phone: "+212 6 55 66 77 88",
    email: "mouna.hassani@example.com",
    address: "44 Rue Moulay Ismail",
    city: "Rabat",
    gender: "Female",
    association: "user",
    associationDetails: { type: "Librarian", username: "mouna.h" },
  },
  {
    personID: 13,
    firstName: "Driss",
    lastName: "Kabbaj",
    nationalNumber: "DK852963",
    phone: "+212 6 44 33 22 11",
    email: "driss.kabbaj@example.com",
    address: "71 Avenue Hassan II",
    city: "Safi",
    gender: "Male",
    association: "none",
    associationDetails: null,
  },
  {
    personID: 14,
    firstName: "Sanaa",
    lastName: "Boukhari",
    nationalNumber: "SB741852",
    phone: "+212 6 77 88 99 00",
    email: "sanaa.boukhari@example.com",
    address: "33 Rue Mohammed VI",
    city: "Tetouan",
    gender: "Female",
    association: "member",
    associationDetails: { type: "Faculty", membershipDate: "2024-11-05" },
  },
  {
    personID: 15,
    firstName: "Tarik",
    lastName: "El Ghazi",
    nationalNumber: "TG951357",
    phone: "+212 6 11 22 33 44",
    email: "tarik.elghazi@example.com",
    address: "28 Rue de la Gare",
    city: "Beni Mellal",
    gender: "Male",
    association: "user",
    associationDetails: { type: "Staff", username: "tarik.g" },
  },
];

// ─── Constants ───────────────────────────────────────────────────────────────
export const AVATAR_COLORS = [
  "bg-green-100 text-green-700",
  "bg-emerald-100 text-emerald-700",
  "bg-teal-100 text-teal-700",
  "bg-lime-100 text-lime-700",
  "bg-cyan-100 text-cyan-700",
  "bg-sky-100 text-sky-700",
  "bg-amber-100 text-amber-700",
  "bg-orange-100 text-orange-700",
  "bg-rose-100 text-rose-700",
  "bg-violet-100 text-violet-700",
  "bg-indigo-100 text-indigo-700",
  "bg-fuchsia-100 text-fuchsia-700",
];

export const SORT_DIR = {
  ASC: "asc",
  DESC: "desc",
  NONE: "none",
};

export const ASSOCIATION_OPTIONS = [
  { value: "all", label: "All" },
  { value: "user", label: "Users" },
  { value: "member", label: "Members" },
  { value: "none", label: "None" },
];

export const GENDER_OPTIONS = [
  { value: "all", label: "All" },
  { value: "Male", label: "Male" },
  { value: "Female", label: "Female" },
];

export const PAGE_SIZE = 10;

export const TABLE_COLUMNS = [
  { key: "firstName", label: "First Name" },
  { key: "lastName", label: "Last Name" },
  { key: "nationalNumber", label: "National ID" },
  { key: "phone", label: "Phone" },
  { key: "email", label: "Email" },
  { key: "address", label: "Address" },
  { key: "city", label: "City" },
  { key: "gender", label: "Gender" },
  { key: "association", label: "Association" },
];

export const DEFAULT_SORT_CONFIG = {
  key: "firstName",
  direction: SORT_DIR.ASC,
};

export const DEFAULT_FILTERS = {
  searchQuery: "",
  associationFilter: "all",
  genderFilter: "all",
  cityFilter: "all",
};